import {
  IconClipboardText,
  IconUsers,
  IconSchool,
  IconNews,
  IconMapPin,
  IconTarget,
  IconCalendar,
  IconFileText,
  IconBook,
  IconDoor,
  IconCreditCard,
  IconTrophy,
  IconTool,
  IconHeartHandshake,
  IconHome,
  IconBuilding,
  IconClock,
  IconPhone,
  IconMail,
  IconChartBar,
  IconGlobe,
  IconScale,
  IconUser,
  IconBook2,
  IconRocket,
  IconPencil,
  IconRobot,
  IconSettings,
  IconMicroscope,
  IconPalette,
  IconLock,
  IconCompass,
  IconStar,
  IconMessageCircle,
  IconBrush,
  IconBallBasketball,
  IconTheater,
  IconBulb,
  IconFlask,
  IconBuildingFactory,
  IconPlane,
  IconReport,
  IconMedal,
  IconSearch,
  IconBookmark,
  IconHeart,
  IconCode,
  IconDeviceDesktop,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconMicrophone,
  IconMusic,
  IconCircleCheck,
  IconFolder,
  IconSun,
  IconLeaf,
  IconPlant,
  IconCar,
  IconTent,
  IconMountain,
  IconCoffee,
  IconGift,
  IconConfetti,
  IconBalloon,
  IconChefHat,
  IconPill,
  IconStethoscope,
  IconBrain,
  IconCalculator,
  IconTrendingUp,
  IconAlarm,
  IconBell,
  IconSpeakerphone,
  IconSatellite,
  IconMap,
  IconTag,
  IconX,
  IconAlertTriangle,
  IconBuildingBank,
  IconBuildingHospital,
  IconClipboardCheck,
  IconShield,
  IconNotes,
  IconId,
  IconLayoutGrid,
  IconSettings2,
  IconCoin,
  IconBriefcase,
  IconRuler,
  IconScissors,
  IconPin,
  IconPaperclip,
  IconNotebook,
  IconCheckbox,
  IconLink,
  IconHelp,
  IconPrinter,
} from '@tabler/icons-react'

// Mapping from emoji string characters to Tabler Icon components
// Used as fallback when data comes from API as emoji strings
export const stringToIcon = {
  '📋': IconClipboardText,
  '📄': IconFileText,
  '📝': IconPencil,
  '📰': IconNews,
  '📚': IconBook2,
  '📖': IconBook,
  '📜': IconReport,
  '✏️': IconPencil,
  '👥': IconUsers,
  '👨‍🏫': IconSchool,
  '👨‍🎓': IconSchool,
  '👨‍💻': IconDeviceLaptop,
  '👩‍🏫': IconSchool,
  '👤': IconUser,
  '🎓': IconSchool,
  '🏆': IconTrophy,
  '🏅': IconMedal,
  '🥇': IconMedal,
  '⭐': IconStar,
  '🎯': IconTarget,
  '🏛️': IconBuilding,
  '🏫': IconSchool,
  '🏠': IconHome,
  '🏭': IconBuildingFactory,
  '🚪': IconDoor,
  '🍽️': IconChefHat,
  '☕': IconCoffee,
  '📢': IconSpeakerphone,
  '📞': IconPhone,
  '📧': IconMail,
  '✉️': IconMail,
  '💬': IconMessageCircle,
  '💻': IconDeviceLaptop,
  '🖥️': IconDeviceDesktop,
  '📱': IconDeviceMobile,
  '🤖': IconRobot,
  '🔒': IconLock,
  '🌐': IconGlobe,
  '🧭': IconCompass,
  '📍': IconMapPin,
  '🗺️': IconMap,
  '💰': IconCoin,
  '💳': IconCreditCard,
  '🔧': IconTool,
  '⚙️': IconSettings,
  '🔩': IconSettings2,
  '🔗': IconLink,
  '📎': IconPaperclip,
  '🏀': IconBallBasketball,
  '⚽': IconBallBasketball,
  '🎾': IconBallBasketball,
  '🎭': IconTheater,
  '🎤': IconMicrophone,
  '🎨': IconPalette,
  '🖌️': IconBrush,
  '🔬': IconMicroscope,
  '📅': IconCalendar,
  '🕐': IconClock,
  '⏰': IconAlarm,
  '🔔': IconBell,
  '🚀': IconRocket,
  '💡': IconBulb,
  '🤝': IconHeartHandshake,
  '🎉': IconConfetti,
  '🎊': IconBalloon,
  '🌍': IconGlobe,
  '⚖️': IconScale,
  '🔍': IconSearch,
  '🔎': IconSearch,
  '📊': IconChartBar,
  '📈': IconTrendingUp,
  '🧮': IconCalculator,
  '💼': IconBriefcase,
  '📦': IconTag,
  '🗃️': IconFolder,
  '🗂️': IconLayoutGrid,
  '📑': IconClipboardCheck,
  '🔖': IconBookmark,
  '🏷️': IconTag,
  '✅': IconCircleCheck,
  '❌': IconX,
  '⚠️': IconAlertTriangle,
  '❤️': IconHeart,
  '🎪': IconTent,
  '✈️': IconPlane,
  '🏨': IconBuilding,
  '🏥': IconBuildingHospital,
  '🏦': IconBuildingBank,
  '📡': IconSatellite,
  '🧪': IconFlask,
  '🛡️': IconShield,
  '🗳️': IconCheckbox,
  '☀️': IconSun,
  '🌆': IconSun,
  '🧠': IconBrain,
  '🎵': IconMusic,
  '🌿': IconLeaf,
  '🌱': IconPlant,
  '🏔️': IconMountain,
  '🚗': IconCar,
  '🚲': IconCar,
  '🎁': IconGift,
  '💊': IconPill,
  '🩺': IconStethoscope,
  '📓': IconNotebook,
  '📒': IconNotes,
  '📃': IconFileText,
  '🖋️': IconPencil,
  '🖊️': IconPencil,
  '🖍️': IconPencil,
  '📁': IconFolder,
  '📂': IconFolder,
  '🗄️': IconSettings2,
  '📌': IconPin,
  '📏': IconRuler,
  '📐': IconRuler,
  '✂️': IconScissors,
  '🔦': IconBulb,
  '📔': IconBook,
  '📕': IconBook,
  '📗': IconBook,
  '📘': IconBook,
  '📙': IconBook,
  '🗞️': IconNews,
  '🐍': IconCode,
  'ℹ️': IconClipboardText,
  '🪪': IconId,
  '🤲': IconHeartHandshake,
  '👪': IconUsers,
  '🖨️': IconDeviceLaptop,
  '🍎': IconCircleCheck,
  '🏃': IconRocket,
  '🎮': IconDeviceLaptop,
  '♿': IconAlertTriangle,
  '🎖️': IconMedal,
  '🚌': IconCar,
  '🎬': IconDeviceDesktop,
  '❓': IconHelp,
  '🏗️': IconBuilding,
  '👨\u200D👩\u200D👧\u200D👦': IconUsers,
  '👨\u200D👩\u200D👧': IconUsers,
  '👩\u200D💻': IconDeviceLaptop,
  '🧑\u200D🔧': IconTool,
}
// Mapping from component name strings (as stored in DB) to actual components
export const nameToIcon = {
  'IconClipboardText': IconClipboardText,
  'IconFileText': IconFileText,
  'IconPencil': IconPencil,
  'IconNews': IconNews,
  'IconBook2': IconBook2,
  'IconBook': IconBook,
  'IconReport': IconReport,
  'IconUsers': IconUsers,
  'IconSchool': IconSchool,
  'IconUser': IconUser,
  'IconTrophy': IconTrophy,
  'IconMedal': IconMedal,
  'IconStar': IconStar,
  'IconTarget': IconTarget,
  'IconBuilding': IconBuilding,
  'IconHome': IconHome,
  'IconBuildingFactory': IconBuildingFactory,
  'IconDoor': IconDoor,
  'IconChefHat': IconChefHat,
  'IconCoffee': IconCoffee,
  'IconSpeakerphone': IconSpeakerphone,
  'IconPhone': IconPhone,
  'IconMail': IconMail,
  'IconMessageCircle': IconMessageCircle,
  'IconDeviceLaptop': IconDeviceLaptop,
  'IconDeviceDesktop': IconDeviceDesktop,
  'IconDeviceMobile': IconDeviceMobile,
  'IconRobot': IconRobot,
  'IconLock': IconLock,
  'IconGlobe': IconGlobe,
  'IconCompass': IconCompass,
  'IconMapPin': IconMapPin,
  'IconMap': IconMap,
  'IconCoin': IconCoin,
  'IconCreditCard': IconCreditCard,
  'IconTool': IconTool,
  'IconSettings': IconSettings,
  'IconSettings2': IconSettings2,
  'IconLink': IconLink,
  'IconPaperclip': IconPaperclip,
  'IconBallBasketball': IconBallBasketball,
  'IconTheater': IconTheater,
  'IconMicrophone': IconMicrophone,
  'IconPalette': IconPalette,
  'IconBrush': IconBrush,
  'IconMicroscope': IconMicroscope,
  'IconCalendar': IconCalendar,
  'IconClock': IconClock,
  'IconAlarm': IconAlarm,
  'IconBell': IconBell,
  'IconRocket': IconRocket,
  'IconBulb': IconBulb,
  'IconHeartHandshake': IconHeartHandshake,
  'IconConfetti': IconConfetti,
  'IconBalloon': IconBalloon,
  'IconScale': IconScale,
  'IconSearch': IconSearch,
  'IconChartBar': IconChartBar,
  'IconTrendingUp': IconTrendingUp,
  'IconCalculator': IconCalculator,
  'IconBriefcase': IconBriefcase,
  'IconTag': IconTag,
  'IconFolder': IconFolder,
  'IconLayoutGrid': IconLayoutGrid,
  'IconClipboardCheck': IconClipboardCheck,
  'IconBookmark': IconBookmark,
  'IconCircleCheck': IconCircleCheck,
  'IconX': IconX,
  'IconAlertTriangle': IconAlertTriangle,
  'IconHeart': IconHeart,
  'IconCode': IconCode,
  'IconPlane': IconPlane,
  'IconSatellite': IconSatellite,
  'IconFlask': IconFlask,
  'IconShield': IconShield,
  'IconNotes': IconNotes,
  'IconId': IconId,
  'IconPrinter': IconPrinter,
  'IconBrain': IconBrain,
  'IconMusic': IconMusic,
  'IconSun': IconSun,
  'IconLeaf': IconLeaf,
  'IconPlant': IconPlant,
  'IconCar': IconCar,
  'IconTent': IconTent,
  'IconMountain': IconMountain,
  'IconGift': IconGift,
  'IconPill': IconPill,
  'IconStethoscope': IconStethoscope,
  'IconNotebook': IconNotebook,
  'IconScissors': IconScissors,
  'IconPin': IconPin,
  'IconRuler': IconRuler,
  'IconHelp': IconHelp,
  'IconCheckbox': IconCheckbox,
  'IconBuildingBank': IconBuildingBank,
  'IconBuildingHospital': IconBuildingHospital,
}

// Helper to render an icon that may be a React component or an emoji string
export function renderIcon(icon, className = 'w-5 h-5') {
  if (typeof icon === 'function') {
    const Icon = icon
    return <Icon className={className} />
  }
  if (typeof icon === 'string') {
    // First try emoji lookup
    const EmojiIcon = stringToIcon[icon]
    if (EmojiIcon) return <EmojiIcon className={className} />
    // Then try component name lookup (e.g. "IconFileText")
    const NameIcon = nameToIcon[icon]
    if (NameIcon) return <NameIcon className={className} />
  }
  return null
}

export default stringToIcon